version: "3"

services:
    db:
        image: mongo
        restart: always
        env_file:
            - server/.env
        volumes:
            - "./data:/data/db"
        ports:
            - "27017:27017"

    server:
        build:
            context: ./server
        env_file:
            - server/.env
        ports:
            - "3000:3000"
        environment:
            - MONGO_URI=${DB_HOST}
        depends_on:
            - db

    client:
        build:
            context: ./client
        env_file:
            - server/.env
        ports:
            - "8888:8888"
        depends_on:
            - server
